spring.application.name=AppraisalSystem
spring.datasource.url=jdbc:mysql://localhost:3306/appraisal_system
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.mvc.pathmatch.use-suffix-pattern=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.notification.email=${MAIL_USERNAME}